# Generated by Django 4.0.5 on 2023-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsite',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
    ]
