# Generated by Django 4.0.5 on 2023-05-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customsite_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsite',
            old_name='site_meta_description',
            new_name='meta_dsescription',
        ),
    ]
