# Generated by Django 4.0.5 on 2023-05-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
